spring.rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # リスナーで例外が起こった時にリキューしない（例外が再実行で解決しないものの場合、リキューしちゃうと無限ループになる）
    listener.simple.default-requeue-rejected: false
    # 古い書き方
    #listener.default-requeue-rejected: false

queue.name: romeo.in

